### PR TITLE
Resource domain support, plus configuration through a property file, plus unit tests.

### PR DESCRIPTION
**Pull request by tatablack**
I'll try to explain the rationale behind my changes.

We use a static resource domain for our files, so I needed to add support for that. Initially I just added a new context parameter, but then I realized we use different domains in our development, testing and production environments, so I needed more flexibility in the configuration of all options.

And I added property-based configuration (see [this issue](https://github.com/tatablack/wro4j-taglib/issues/1), the updated [README.md](https://github.com/tatablack/wro4j-taglib/blob/domain-support/README.md) file - or the code itself - for the loading sequence).

After that, since there were no unit tests, I had to add them too (my team would not have considered using an external library without tests).

I also updated the README file to reflect my changes. I'd be glad to update your companion project (https://github.com/Orange-OpenSource/test-release-wro4j-buildtime) too; we can discuss about it later, I suppose.

Let me know what you think, and thanks for your library, anyway..  :+1:

### CODE REVIEW

**Comment by julienw** [comment]
Wow, thanks, that feels right :-)

**Comment by bidorffOL** [comment]
I'll give it a shot as soon as possible, but I'm on holiday right now and I might not be able to do so before January 2nd.

**Comment by bidorffOL** [comment]
I just took a look at your code, it looks great! I will probably just have to ajust the indentation here and there to have uniformity along the projet.

**Comment by tatablack** [comment]
Thanks for looking at the code. I'm on holiday too, so I understand
perfectly... :-)

Regarding the indentation, yes, I tried to keep tabs instead of spaces but
I may have missed some, and I think the project has a stricter
character-per-column convention than I'm used to.

Moreover, I'm pretty sure a couple of unit tests might be improved, but I
thought it would be better to push now and refactor later.

Anyway, enjoy the rest of your holidays! (both David and Julien) ;-)

A.

**Comment by tatablack** [comment]
Hello again. Any updates? Is there any way I could still help?

**Comment by bidorffOL** [comment]
Well, to be honest, I have been drowning in work lately. However, I took a look at your commit and I only met one problem: one of the test does not pass on my computer:

At the beginning of _com.orange.wro.taglib.config.WroTagLibPropertiesTest.java_, you initialize the _PROPERTIES_CUSTOM_LOCATION_ using the _java.io.tmpdir_ property. However, it seems that on some configurations (including mine), this property doesn't end with a file separator. In my case, it results with a tmp folder set to _/tmpwro4jtest_ instead of _/tmp/wro4jtest_. I tried to replace this line by:

``` java
PROPERTIES_CUSTOM_LOCATION = tempFolder.append(System.getProperty("file.separator")).append("wro4jtest").toString();
```

But I can't seem to find how to add my commit to your pull request (I'm still new at GitHub :( ) ...

**Comment by tatablack** [comment]
You're right, sorry; I didn't know that property was unreliable. I pushed a change myself (which gets incorporated automatically in the pull request), should be fixed now.

**Comment by b0z0** [comment]
Great thank you, I'll give it a try this morning, then I'll try to fix a few bug requests before releasing a new version that will include your pull request. Again, thank you !

**Pull request merged**
